#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_insights = env_modules.Clone()

module_obj = []

env_insights.add_source_files(module_obj, "*.cpp")
env_insights.add_source_files(module_obj, "insights_core/*.cpp")
env_insights.add_source_files(module_obj, "channels/*.cpp")
env_insights.add_source_files(module_obj, "gpu/*.cpp")
env_insights.add_source_files(module_obj, "scripting/*.cpp")
env_insights.add_source_files(module_obj, "tools/*.cpp")
env_insights.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj
