/**************************************************************************/
/*  nanite_gpu_pipeline.cpp                                               */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#include "nanite/gpu/nanite_gpu_pipeline.h"

#include "core/error/error_macros.h"
#include "nanite/gpu/nanite_mesh_data.h"
#include "servers/rendering/rendering_device.h"
#include "servers/rendering/rendering_device_binds.h"

// Generated by the GLSL_HEADER scons builder from nanite/shaders/.
// Each defines a raw GLSL source string parsed at runtime via RDShaderFile.
#include "nanite/shaders/nanite_cull.glsl.gen.h"
#include "nanite/shaders/nanite_composite.glsl.gen.h"
#include "nanite/shaders/nanite_material_resolve.glsl.gen.h"
#include "nanite/shaders/nanite_rasterize.glsl.gen.h"

namespace {

// Must match the `Params` push constant block in nanite_cull.glsl.
// Camera matrices live in a UBO, not here (see MAX_PUSH_CONSTANT_SIZE note).
// Layout (std430, model_matrix first to keep mat4 16-aligned at offset 0):
//   offset 0:  mat4 model_matrix (64 B)
//   offset 64: ivec2 screen_size (8 B)
//   offset 72: float error_threshold (4 B)
//   offset 76: uint bvh_node_count (4 B)
//   offset 80: uint cluster_count (4 B)
//   offset 84: uint _pad (4 B)
//   total: 88 B (rounded up to 16-multiple → 96 B by std430 rules)
struct CullPushConstant {
	float model_matrix[16]; // Task 1.16.6 — per-instance world transform
	int32_t screen_size[2];
	float error_threshold;
	uint32_t bvh_node_count;
	uint32_t cluster_count;
	uint32_t _pad;
};

// Must match the `Params` push constant block in nanite_rasterize.glsl.
// Layout (std430): mat4 model_matrix (64B) + ivec2 screen_size (8B) +
// uint visible_count (4B) + uint _pad (4B) = 80 B (rounded to 80 by std430).
struct RasterizePushConstant {
	float model_matrix[16]; // Task 1.16.6 — per-instance world transform
	int32_t screen_size[2];
	uint32_t visible_count;
	uint32_t _pad;
};

// Must match the `Params` push constant block in nanite_material_resolve.glsl.
// Layout (std430): mat4 model_matrix (64B) + ivec2 screen_size (8B) +
// uint debug_mode (4B) + uint _pad (4B) = 80 B  +
// vec3 light_dir (12B) + float light_energy (4B) +
// vec3 light_color (12B) + uint _pad2 (4B) = 32 B
// Total = 112 B (within MAX_PUSH_CONSTANT_SIZE == 128).
struct MaterialResolvePushConstant {
	float model_matrix[16]; // Task 1.16.6 — per-instance world transform
	int32_t screen_size[2];
	uint32_t debug_mode;
	uint32_t _pad;
	float light_dir[3]; // world space, normalized, toward surface
	float light_energy; // DirectionalLight3D.light_energy
	float light_color[3]; // linear RGB, pre-multiplied by energy
	uint32_t _pad2;
};

// Must match the `Params` push constant block in nanite_composite.glsl.
// Layout (std430): ivec2 screen_size (8B) + 2 uint _pad (8B) = 16 B.
struct CompositePushConstant {
	int32_t screen_size[2];
	uint32_t _pad0;
	uint32_t _pad1;
};

// Camera UBO payload: two column-major mat4s (128 bytes). Matches the
// `CameraUniform` block declared in nanite_cull.glsl.
struct CameraUniform {
	float view_matrix[16];
	float projection[16];
};

// Task 1.16.6 — column-major identity matrix used when p_model_matrix is
// nullptr (no per-instance transform). Stored in static const so callers
// never need to allocate a stack buffer just to pass identity.
static const float IDENTITY_MATRIX[16] = {
	1.0f, 0.0f, 0.0f, 0.0f,
	0.0f, 1.0f, 0.0f, 0.0f,
	0.0f, 0.0f, 1.0f, 0.0f,
	0.0f, 0.0f, 0.0f, 1.0f
};

// Copies p_src (16 floats, column-major) into p_dst, or fills with identity
// when p_src is nullptr.
static inline void copy_model_matrix(float *p_dst, const float *p_src) {
	if (p_src != nullptr) {
		memcpy(p_dst, p_src, sizeof(float) * 16);
	} else {
		memcpy(p_dst, IDENTITY_MATRIX, sizeof(float) * 16);
	}
}

// Parses an embedded GLSL string into an RDShaderFile and creates a shader +
// compute pipeline from it. Mirrors NaniteHZB::init. Returns false on error.
bool _create_compute_shader_and_pipeline(RenderingDevice *p_rd, const char *p_glsl, const char *p_label,
		RID &r_shader, RID &r_pipeline) {
	Ref<RDShaderFile> shader_file;
	shader_file.instantiate();
	Error err = shader_file->parse_versions_from_text(p_glsl);
	if (err != OK) {
		shader_file->print_errors(p_label);
		return false;
	}
	r_shader = p_rd->shader_create_from_spirv(shader_file->get_spirv_stages());
	if (!r_shader.is_valid()) {
		return false;
	}
	r_pipeline = p_rd->compute_pipeline_create(r_shader);
	return r_pipeline.is_valid();
}

} // namespace

void NaniteGPUPipeline::init(RenderingDevice *p_rd) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(initialized);

	bool ok = true;
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_cull_shader_glsl, "nanite_cull", cull_shader, cull_pipeline);
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_rasterize_shader_glsl, "nanite_rasterize", rasterize_shader, rasterize_pipeline);
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_material_resolve_shader_glsl, "nanite_material_resolve", material_resolve_shader, material_resolve_pipeline);
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_composite_shader_glsl, "nanite_composite", composite_shader, composite_pipeline);
	if (!ok) {
		ERR_FAIL_MSG("NaniteGPUPipeline: failed to create one or more compute pipelines.");
	}

	// Nearest + clamp-to-edge sampler for the HZB texture bound in the cull set.
	RD::SamplerState sampler_state;
	sampler_state.mag_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.min_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.mip_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.repeat_u = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_v = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_w = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	hzb_sampler = p_rd->sampler_create(sampler_state);
	ERR_FAIL_COND(!hzb_sampler.is_valid());

	// Persistent camera UBO (updated each frame via buffer_update).
	camera_ubo = p_rd->uniform_buffer_create(sizeof(CameraUniform));
	ERR_FAIL_COND(!camera_ubo.is_valid());

	// 1x1 R32_SFLOAT fallback for the HZB texture slot until the first HZB is
	// built (the cull shader declares sampler2D hzb_texture; the binding must
	// always point at a valid R32_SFLOAT texture).
	RD::TextureFormat dummy_tf;
	dummy_tf.format = RD::DATA_FORMAT_R32_SFLOAT;
	dummy_tf.width = 1;
	dummy_tf.height = 1;
	dummy_tf.texture_type = RD::TEXTURE_TYPE_2D;
	dummy_tf.usage_bits = RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT;
	dummy_hzb_texture = p_rd->texture_create(dummy_tf, RD::TextureView());
	ERR_FAIL_COND(!dummy_hzb_texture.is_valid());
	PackedByteArray zero;
	zero.resize(sizeof(float));
	zero.fill(0);
	p_rd->texture_update(dummy_hzb_texture, 0, zero);

	hzb.init(p_rd);

	initialized = true;
}

void NaniteGPUPipeline::_free_screen_buffers(RenderingDevice *p_rd) {
	// Screen buffer resize invalidates all uniform sets that reference
	// vis_buffer / depth_buffer / color_buffer.
	_free_uniform_sets(p_rd);
	if (p_rd == nullptr) {
		vis_buffer = RID();
		depth_buffer = RID();
		color_buffer = RID();
		current_width = 0;
		current_height = 0;
		return;
	}
	if (vis_buffer.is_valid()) {
		p_rd->free_rid(vis_buffer);
		vis_buffer = RID();
	}
	if (depth_buffer.is_valid()) {
		p_rd->free_rid(depth_buffer);
		depth_buffer = RID();
	}
	if (color_buffer.is_valid()) {
		p_rd->free_rid(color_buffer);
		color_buffer = RID();
	}
	current_width = 0;
	current_height = 0;
}

void NaniteGPUPipeline::_free_visible_buffers(RenderingDevice *p_rd) {
	// Visible buffer resize invalidates cull + rasterize uniform sets.
	_free_uniform_sets(p_rd);
	if (p_rd == nullptr) {
		visible_clusters_buffer = RID();
		visible_count_buffer = RID();
		current_visible_capacity = 0;
		return;
	}
	if (visible_clusters_buffer.is_valid()) {
		p_rd->free_rid(visible_clusters_buffer);
		visible_clusters_buffer = RID();
	}
	if (visible_count_buffer.is_valid()) {
		p_rd->free_rid(visible_count_buffer);
		visible_count_buffer = RID();
	}
	current_visible_capacity = 0;
}

void NaniteGPUPipeline::_free_uniform_sets(RenderingDevice *p_rd) {
	// Invalidate all cached uniform sets so they get rebuilt on next dispatch.
	// Called on screen buffer resize, visible buffer resize, mesh swap, or
	// pipeline cleanup.
	if (p_rd == nullptr) {
		cull_uniform_set = RID();
		rasterize_uniform_set = RID();
		material_resolve_uniform_set = RID();
		composite_uniform_set = RID();
		composite_last_engine_target = RID();
		last_mesh_cluster_ssbo = RID();
		last_mesh_bvh_ssbo = RID();
		last_mesh_vertex_ssbo = RID();
		last_hzb_texture = RID();
		return;
	}
	if (cull_uniform_set.is_valid()) {
		p_rd->free_rid(cull_uniform_set);
		cull_uniform_set = RID();
	}
	if (rasterize_uniform_set.is_valid()) {
		p_rd->free_rid(rasterize_uniform_set);
		rasterize_uniform_set = RID();
	}
	if (material_resolve_uniform_set.is_valid()) {
		p_rd->free_rid(material_resolve_uniform_set);
		material_resolve_uniform_set = RID();
	}
	if (composite_uniform_set.is_valid()) {
		p_rd->free_rid(composite_uniform_set);
		composite_uniform_set = RID();
	}
	composite_last_engine_target = RID();
	last_mesh_cluster_ssbo = RID();
	last_mesh_bvh_ssbo = RID();
	last_mesh_vertex_ssbo = RID();
	last_hzb_texture = RID();
}

void NaniteGPUPipeline::cleanup(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		return;
	}

	_free_screen_buffers(p_rd);
	_free_visible_buffers(p_rd);

	hzb.cleanup(p_rd);

	if (dummy_hzb_texture.is_valid()) {
		p_rd->free_rid(dummy_hzb_texture);
		dummy_hzb_texture = RID();
	}
	if (camera_ubo.is_valid()) {
		p_rd->free_rid(camera_ubo);
		camera_ubo = RID();
	}
	if (hzb_sampler.is_valid()) {
		p_rd->free_rid(hzb_sampler);
		hzb_sampler = RID();
	}
	if (material_resolve_pipeline.is_valid()) {
		p_rd->free_rid(material_resolve_pipeline);
		material_resolve_pipeline = RID();
	}
	if (material_resolve_shader.is_valid()) {
		p_rd->free_rid(material_resolve_shader);
		material_resolve_shader = RID();
	}
	if (composite_pipeline.is_valid()) {
		p_rd->free_rid(composite_pipeline);
		composite_pipeline = RID();
	}
	if (composite_shader.is_valid()) {
		p_rd->free_rid(composite_shader);
		composite_shader = RID();
	}
	if (rasterize_pipeline.is_valid()) {
		p_rd->free_rid(rasterize_pipeline);
		rasterize_pipeline = RID();
	}
	if (rasterize_shader.is_valid()) {
		p_rd->free_rid(rasterize_shader);
		rasterize_shader = RID();
	}
	if (cull_pipeline.is_valid()) {
		p_rd->free_rid(cull_pipeline);
		cull_pipeline = RID();
	}
	if (cull_shader.is_valid()) {
		p_rd->free_rid(cull_shader);
		cull_shader = RID();
	}

	initialized = false;
}

void NaniteGPUPipeline::ensure_screen_buffers(RenderingDevice *p_rd, int p_width, int p_height) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(p_width <= 0 || p_height <= 0);

	if (p_width == current_width && p_height == current_height && vis_buffer.is_valid() && depth_buffer.is_valid() && color_buffer.is_valid()) {
		return;
	}

	_free_screen_buffers(p_rd);

	current_width = p_width;
	current_height = p_height;

	// vis_buffer: R32_UINT, one uint per pixel = (cluster_id << 8 | triangle_id).
	// Storage for imageStore (rasterize) + sampling/copy for downstream passes.
	// Task 1.16.8 — CAN_COPY_TO_BIT so dispatch_rasterize can texture_clear it.
	RD::TextureFormat vis_tf;
	vis_tf.format = RD::DATA_FORMAT_R32_UINT;
	vis_tf.width = p_width;
	vis_tf.height = p_height;
	vis_tf.texture_type = RD::TEXTURE_TYPE_2D;
	vis_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT | RD::TEXTURE_USAGE_CAN_COPY_TO_BIT;
	vis_buffer = p_rd->texture_create(vis_tf, RD::TextureView());
	ERR_FAIL_COND(!vis_buffer.is_valid());

	// depth_buffer: R32_SFLOAT, written by the rasterize pass and copied into
	// HZB mip 0 by dispatch_hzb_build (so it needs CAN_COPY_FROM_BIT).
	// Task 1.16.8 — CAN_COPY_TO_BIT so dispatch_rasterize can clear to 1.0 (far).
	// Storage usage allows imageLoad (compare-then-store depth test).
	RD::TextureFormat depth_tf;
	depth_tf.format = RD::DATA_FORMAT_R32_SFLOAT;
	depth_tf.width = p_width;
	depth_tf.height = p_height;
	depth_tf.texture_type = RD::TEXTURE_TYPE_2D;
	depth_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT | RD::TEXTURE_USAGE_CAN_COPY_TO_BIT;
	depth_buffer = p_rd->texture_create(depth_tf, RD::TextureView());
	ERR_FAIL_COND(!depth_buffer.is_valid());

	// color_buffer: RGBA8 UNORM, written by material_resolve (Task 1.11) and
	// read back by tests / future compositing into the engine color target.
	RD::TextureFormat color_tf;
	color_tf.format = RD::DATA_FORMAT_R8G8B8A8_UNORM;
	color_tf.width = p_width;
	color_tf.height = p_height;
	color_tf.texture_type = RD::TEXTURE_TYPE_2D;
	color_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;
	color_buffer = p_rd->texture_create(color_tf, RD::TextureView());
	ERR_FAIL_COND(!color_buffer.is_valid());
}

RID NaniteGPUPipeline::dispatch_cull(RenderingDevice *p_rd, const CullParams &p_params, const NaniteMeshData *p_mesh_data) {
	ERR_FAIL_NULL_V(p_rd, RID());
	ERR_FAIL_COND_V(!initialized, RID());
	ERR_FAIL_NULL_V(p_mesh_data, RID());
	ERR_FAIL_COND_V(!p_mesh_data->is_gpu_uploaded(), RID());
	ERR_FAIL_COND_V(!cull_pipeline.is_valid(), RID());

	const uint32_t cluster_count = p_params.cluster_count;

	// (Re)allocate the visible-clusters scratch buffer if it must grow. The
	// count buffer is a single uint32; it is zeroed before every dispatch.
	if (cluster_count > current_visible_capacity || !visible_clusters_buffer.is_valid() || !visible_count_buffer.is_valid()) {
		_free_visible_buffers(p_rd);

		// Zero-sized storage buffers cause driver issues, so keep at least 1.
		uint32_t capacity = MAX(cluster_count, 1u);
		visible_clusters_buffer = p_rd->storage_buffer_create(capacity * sizeof(uint32_t));
		ERR_FAIL_COND_V(!visible_clusters_buffer.is_valid(), RID());
		visible_count_buffer = p_rd->storage_buffer_create(sizeof(uint32_t));
		ERR_FAIL_COND_V(!visible_count_buffer.is_valid(), RID());
		current_visible_capacity = capacity;
	}

	// Zero the visible counter so the shader's atomicAdd starts from 0.
	uint32_t zero_count = 0;
	p_rd->buffer_update(visible_count_buffer, 0, sizeof(uint32_t), &zero_count);

	// Refresh the camera UBO with this frame's matrices (column-major float[16]).
	CameraUniform cam;
	memcpy(cam.view_matrix, p_params.view_matrix, sizeof(cam.view_matrix));
	memcpy(cam.projection, p_params.projection, sizeof(cam.projection));
	p_rd->buffer_update(camera_ubo, 0, sizeof(CameraUniform), &cam);

	// HZB texture may not exist yet on the first frame; fall back to the 1x1
	// dummy so the sampler2D binding is always valid.
	RID hzb_tex = hzb.get_hzb_texture();
	if (!hzb_tex.is_valid()) {
		hzb_tex = dummy_hzb_texture;
	}

	// Build the cull uniform set (set 0): clusters, bvh, hzb+sampler, visible
	// output, visible count, camera UBO.
	// Reuse cached uniform set if none of its dependent RIDs changed.
	bool need_rebuild = !cull_uniform_set.is_valid();
	if (last_mesh_cluster_ssbo != p_mesh_data->get_cluster_ssbo()) {
		need_rebuild = true;
		last_mesh_cluster_ssbo = p_mesh_data->get_cluster_ssbo();
	}
	if (last_mesh_bvh_ssbo != p_mesh_data->get_bvh_ssbo()) {
		need_rebuild = true;
		last_mesh_bvh_ssbo = p_mesh_data->get_bvh_ssbo();
	}
	if (last_hzb_texture != hzb_tex) {
		need_rebuild = true;
		last_hzb_texture = hzb_tex;
	}
	if (need_rebuild) {
		if (cull_uniform_set.is_valid()) {
			p_rd->free_rid(cull_uniform_set);
		}
		Vector<RD::Uniform> uniforms;
		{
			RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 0, p_mesh_data->get_cluster_ssbo());
			RD::Uniform u_bvh(RD::UNIFORM_TYPE_STORAGE_BUFFER, 1, p_mesh_data->get_bvh_ssbo());
			RD::Uniform u_hzb(RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE, 2, Vector<RID>({ hzb_sampler, hzb_tex }));
			RD::Uniform u_visible(RD::UNIFORM_TYPE_STORAGE_BUFFER, 3, visible_clusters_buffer);
			RD::Uniform u_count(RD::UNIFORM_TYPE_STORAGE_BUFFER, 4, visible_count_buffer);
			RD::Uniform u_camera(RD::UNIFORM_TYPE_UNIFORM_BUFFER, 5, camera_ubo);
			uniforms.push_back(u_clusters);
			uniforms.push_back(u_bvh);
			uniforms.push_back(u_hzb);
			uniforms.push_back(u_visible);
			uniforms.push_back(u_count);
			uniforms.push_back(u_camera);
		}
		cull_uniform_set = p_rd->uniform_set_create(uniforms, cull_shader, 0);
	}
	ERR_FAIL_COND_V(!cull_uniform_set.is_valid(), RID());

	CullPushConstant pc;
	copy_model_matrix(pc.model_matrix, p_params.model_matrix); // Task 1.16.6
	pc.screen_size[0] = p_params.screen_size[0];
	pc.screen_size[1] = p_params.screen_size[1];
	pc.error_threshold = p_params.error_threshold;
	pc.bvh_node_count = p_params.bvh_node_count;
	pc.cluster_count = cluster_count;
	pc._pad = 0;

	// dispatch_threads covers cluster_count invocations (workgroup 64).
	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, cull_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, cull_uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(CullPushConstant));
	p_rd->compute_list_dispatch_threads(compute_list, MAX(cluster_count, 1u), 1, 1);
	p_rd->compute_list_end();

	// NOTE: 显式 barrier 已移除。RenderingDevice 4.x 会自动在
	// compute_list_end() 与下一个 dispatch/copy 之间插入正确的
	// 内存屏障,显式调用 p_rd->barrier() 会触发废弃警告。

	return visible_clusters_buffer;
}

void NaniteGPUPipeline::dispatch_rasterize(RenderingDevice *p_rd, const RID &p_visible_buffer, uint32_t p_visible_count, const NaniteMeshData *p_mesh_data, const float *p_model_matrix) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!p_visible_buffer.is_valid());
	ERR_FAIL_NULL(p_mesh_data);
	ERR_FAIL_COND(!p_mesh_data->is_gpu_uploaded());
	ERR_FAIL_COND(!rasterize_pipeline.is_valid());
	ERR_FAIL_COND(!vis_buffer.is_valid());
	ERR_FAIL_COND(!depth_buffer.is_valid());

	// Task 1.16.8 — clear vis_buffer to 0 (no geometry) and depth_buffer to
	// 1.0 (far) before rasterization. The shader uses imageLoad(depth_buffer)
	// for a non-atomic compare-then-store, so the depth must start at far.
	p_rd->texture_clear(vis_buffer, Color(0, 0, 0, 0), 0, 1, 0, 1);
	p_rd->texture_clear(depth_buffer, Color(1.0, 0, 0, 0), 0, 1, 0, 1);
	// NOTE: 显式 barrier 已移除(RenderingDevice 自动插入)。

	// Build the rasterize uniform set (set 0):
	//   binding 0: visible_clusters_buffer (SSBO)
	//   binding 1: cluster_ssbo (SSBO, uint32[] — 17 uints per cluster)
	//   binding 2: vertex_ssbo (SSBO, raw stride 32 B)
	//   binding 3: vis_buffer (image, r32ui, writeonly)
	//   binding 4: depth_buffer (image, r32f, read+write)
	//   binding 5: camera_ubo (UBO, view + projection)
	//   binding 6: meshlet_vertices_ssbo (SSBO, uint32[])
	//   binding 7: meshlet_triangles_ssbo (SSBO, packed uint8[])
	// Reuse cached uniform set if none of its dependent RIDs changed.
	// Depends on p_visible_buffer (per-mesh), mesh SSBOs (per-mesh), and
	// vis_buffer/depth_buffer (per-resize). All tracked via last_* fields.
	bool need_rebuild = !rasterize_uniform_set.is_valid();
	if (last_mesh_vertex_ssbo != p_mesh_data->get_vertex_ssbo()) {
		need_rebuild = true;
		last_mesh_vertex_ssbo = p_mesh_data->get_vertex_ssbo();
	}
	// p_visible_buffer is the cull output (visible_clusters_buffer owned
	// by this pipeline); it changes when visible buffers resize, which
	// already invalidates via _free_visible_buffers -> _free_uniform_sets.
	if (need_rebuild) {
		if (rasterize_uniform_set.is_valid()) {
			p_rd->free_rid(rasterize_uniform_set);
		}
		Vector<RD::Uniform> uniforms;
		{
			RD::Uniform u_visible(RD::UNIFORM_TYPE_STORAGE_BUFFER, 0, p_visible_buffer);
			RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 1, p_mesh_data->get_cluster_ssbo());
			RD::Uniform u_vertices(RD::UNIFORM_TYPE_STORAGE_BUFFER, 2, p_mesh_data->get_vertex_ssbo());
			RD::Uniform u_vis(RD::UNIFORM_TYPE_IMAGE, 3, vis_buffer);
			RD::Uniform u_depth(RD::UNIFORM_TYPE_IMAGE, 4, depth_buffer);
			RD::Uniform u_camera(RD::UNIFORM_TYPE_UNIFORM_BUFFER, 5, camera_ubo);
			RD::Uniform u_mv(RD::UNIFORM_TYPE_STORAGE_BUFFER, 6, p_mesh_data->get_meshlet_vertices_ssbo());
			RD::Uniform u_mt(RD::UNIFORM_TYPE_STORAGE_BUFFER, 7, p_mesh_data->get_meshlet_triangles_ssbo());
			uniforms.push_back(u_visible);
			uniforms.push_back(u_clusters);
			uniforms.push_back(u_vertices);
			uniforms.push_back(u_vis);
			uniforms.push_back(u_depth);
			uniforms.push_back(u_camera);
			uniforms.push_back(u_mv);
			uniforms.push_back(u_mt);
		}
		rasterize_uniform_set = p_rd->uniform_set_create(uniforms, rasterize_shader, 0);
	}
	ERR_FAIL_COND(!rasterize_uniform_set.is_valid());

	RasterizePushConstant pc;
	copy_model_matrix(pc.model_matrix, p_model_matrix); // Task 1.16.6
	pc.screen_size[0] = current_width;
	pc.screen_size[1] = current_height;
	pc.visible_count = p_visible_count;
	pc._pad = 0;

	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, rasterize_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, rasterize_uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(RasterizePushConstant));
	p_rd->compute_list_dispatch_threads(compute_list, MAX(p_visible_count, 1u), 1, 1);
	p_rd->compute_list_end();

	// NOTE: 显式 barrier 已移除。vis_buffer/depth_buffer 写入对
	// dispatch_hzb_build 可见由 RenderingDevice 自动屏障保证。
}

void NaniteGPUPipeline::dispatch_hzb_build(RenderingDevice *p_rd, const RID &p_depth_texture) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	hzb.build(p_rd, p_depth_texture);
}

void NaniteGPUPipeline::dispatch_material_resolve(RenderingDevice *p_rd, const RID &p_vis_buffer, const NaniteMeshData *p_mesh_data, int p_debug_mode, const float *p_model_matrix, const Vector3 &p_light_dir, float p_light_energy, const Color &p_light_color) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!material_resolve_pipeline.is_valid());
	ERR_FAIL_COND(!vis_buffer.is_valid());
	ERR_FAIL_COND(!color_buffer.is_valid());
	ERR_FAIL_NULL(p_mesh_data);
	ERR_FAIL_COND(!p_mesh_data->is_gpu_uploaded());

	// Use the pipeline's internal vis_buffer if p_vis_buffer is invalid
	// (caller convenience — most callers drive the full pipeline internally).
	RID vis = p_vis_buffer.is_valid() ? p_vis_buffer : vis_buffer;

	// Build the material-resolve uniform set (set 0):
	//   binding 0: vis_buffer (readonly uimage2D, r32ui)
	//   binding 1: color_buffer (writeonly image2D, rgba8)
	//   binding 2: cluster_ssbo (storage buffer, for material lookup)
	//   binding 3: vertex_ssbo (storage buffer, for barycentric interp)
	//   binding 4: materials_ssbo (storage buffer, base_color lookup)
	//   binding 5: meshlet_vertices_ssbo (Task 1.16.9 — global vertex indices)
	//   binding 6: meshlet_triangles_ssbo (Task 1.16.9 — local triangle indices)
	//   binding 7: camera_ubo (Task 1.16.9 — view + projection for re-projection)
	// Reuse cached uniform set if mesh SSBOs haven't changed (vis/color are
	// owned by pipeline and invalidated on resize via _free_uniform_sets).
	bool need_rebuild = !material_resolve_uniform_set.is_valid();
	if (last_mesh_vertex_ssbo != p_mesh_data->get_vertex_ssbo()) {
		need_rebuild = true;
		last_mesh_vertex_ssbo = p_mesh_data->get_vertex_ssbo();
	}
	if (need_rebuild) {
		if (material_resolve_uniform_set.is_valid()) {
			p_rd->free_rid(material_resolve_uniform_set);
		}
		Vector<RD::Uniform> uniforms;
		{
			RD::Uniform u_vis(RD::UNIFORM_TYPE_IMAGE, 0, vis);
			RD::Uniform u_color(RD::UNIFORM_TYPE_IMAGE, 1, color_buffer);
			RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 2, p_mesh_data->get_cluster_ssbo());
			RD::Uniform u_vertices(RD::UNIFORM_TYPE_STORAGE_BUFFER, 3, p_mesh_data->get_vertex_ssbo());
			RD::Uniform u_materials(RD::UNIFORM_TYPE_STORAGE_BUFFER, 4, p_mesh_data->get_materials_ssbo());
			RD::Uniform u_mv(RD::UNIFORM_TYPE_STORAGE_BUFFER, 5, p_mesh_data->get_meshlet_vertices_ssbo());
			RD::Uniform u_mt(RD::UNIFORM_TYPE_STORAGE_BUFFER, 6, p_mesh_data->get_meshlet_triangles_ssbo());
			RD::Uniform u_camera(RD::UNIFORM_TYPE_UNIFORM_BUFFER, 7, camera_ubo);
			uniforms.push_back(u_vis);
			uniforms.push_back(u_color);
			uniforms.push_back(u_clusters);
			uniforms.push_back(u_vertices);
			uniforms.push_back(u_materials);
			uniforms.push_back(u_mv);
			uniforms.push_back(u_mt);
			uniforms.push_back(u_camera);
		}
		material_resolve_uniform_set = p_rd->uniform_set_create(uniforms, material_resolve_shader, 0);
	}
	ERR_FAIL_COND(!material_resolve_uniform_set.is_valid());

	MaterialResolvePushConstant pc;
	copy_model_matrix(pc.model_matrix, p_model_matrix); // Task 1.16.6
	pc.screen_size[0] = current_width;
	pc.screen_size[1] = current_height;
	pc.debug_mode = (uint32_t)p_debug_mode;
	pc._pad = 0;
	// 光照参数(从场景 DirectionalLight3D 采集)。
	pc.light_dir[0] = p_light_dir.x;
	pc.light_dir[1] = p_light_dir.y;
	pc.light_dir[2] = p_light_dir.z;
	pc.light_energy = p_light_energy;
	// light_color 预乘 energy,这样 shader 端只需 NdotL * light_color。
	pc.light_color[0] = p_light_color.r * p_light_energy;
	pc.light_color[1] = p_light_color.g * p_light_energy;
	pc.light_color[2] = p_light_color.b * p_light_energy;
	pc._pad2 = 0;

	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, material_resolve_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, material_resolve_uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(MaterialResolvePushConstant));
	// dispatch_threads covers all screen pixels (workgroup 8x8).
	p_rd->compute_list_dispatch_threads(compute_list, current_width, current_height, 1);
	p_rd->compute_list_end();
}

void NaniteGPUPipeline::dispatch_composite(RenderingDevice *p_rd, const RID &p_engine_color_target) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!composite_pipeline.is_valid());
	ERR_FAIL_COND(!vis_buffer.is_valid());
	ERR_FAIL_COND(!color_buffer.is_valid());
	ERR_FAIL_COND(!p_engine_color_target.is_valid());

	// NOTE: 显式 barrier 已移除。material_resolve 写入对 composite 可见
	// 由 RenderingDevice 自动屏障保证。

	// Composite uniform set (set 0):
	//   binding 0: vis_buffer (readonly uimage2D, r32ui) — mask
	//   binding 1: color_buffer (readonly image2D, rgba8) — source color
	//   binding 2: engine_color_target (writeonly image2D, rgba8) — destination
	// Reuse cached uniform set; rebuild only when engine target RID changes
	// (vis_buffer/color_buffer changes are covered by _free_uniform_sets on
	// screen buffer resize).
	bool need_rebuild = !composite_uniform_set.is_valid();
	if (composite_last_engine_target != p_engine_color_target) {
		need_rebuild = true;
		composite_last_engine_target = p_engine_color_target;
	}
	if (need_rebuild) {
		if (composite_uniform_set.is_valid()) {
			p_rd->free_rid(composite_uniform_set);
		}
		Vector<RD::Uniform> uniforms;
		{
			RD::Uniform u_vis(RD::UNIFORM_TYPE_IMAGE, 0, vis_buffer);
			RD::Uniform u_color(RD::UNIFORM_TYPE_IMAGE, 1, color_buffer);
			RD::Uniform u_target(RD::UNIFORM_TYPE_IMAGE, 2, p_engine_color_target);
			uniforms.push_back(u_vis);
			uniforms.push_back(u_color);
			uniforms.push_back(u_target);
		}
		composite_uniform_set = p_rd->uniform_set_create(uniforms, composite_shader, 0);
	}
	ERR_FAIL_COND(!composite_uniform_set.is_valid());

	CompositePushConstant pc;
	pc.screen_size[0] = current_width;
	pc.screen_size[1] = current_height;
	pc._pad0 = 0;
	pc._pad1 = 0;

	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, composite_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, composite_uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(CompositePushConstant));
	// dispatch_threads covers all screen pixels (workgroup 8x8).
	p_rd->compute_list_dispatch_threads(compute_list, current_width, current_height, 1);
	p_rd->compute_list_end();
}
