/**************************************************************************/
/*  nanite_gpu_pipeline.cpp                                               */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#include "gpu/nanite_gpu_pipeline.h"

#include "core/error/error_macros.h"
#include "gpu/nanite_mesh_data.h"
#include "servers/rendering/rendering_device.h"
#include "servers/rendering/rendering_device_binds.h"

// Generated by the GLSL_HEADER scons builder from nanite/shaders/.
// Each defines a raw GLSL source string parsed at runtime via RDShaderFile.
#include "shaders/nanite_cull.glsl.gen.h"
#include "shaders/nanite_material_resolve.glsl.gen.h"
#include "shaders/nanite_rasterize.glsl.gen.h"

namespace {

// Must match the `Params` push constant block in nanite_cull.glsl.
// Camera matrices live in a UBO, not here (see MAX_PUSH_CONSTANT_SIZE note).
struct CullPushConstant {
	int32_t screen_size[2];
	float error_threshold;
	uint32_t bvh_node_count;
	uint32_t cluster_count;
	uint32_t _pad; // keep the struct a multiple of 8 (std430 ivec2 alignment)
};

// Must match the `Params` push constant block in nanite_rasterize.glsl.
struct RasterizePushConstant {
	int32_t screen_size[2];
	uint32_t visible_count;
	uint32_t _pad;
};

// Must match the `Params` push constant block in nanite_material_resolve.glsl.
struct MaterialResolvePushConstant {
	int32_t screen_size[2];
	uint32_t debug_mode;
	uint32_t _pad;
};

// Camera UBO payload: two column-major mat4s (128 bytes). Matches the
// `CameraUniform` block declared in nanite_cull.glsl.
struct CameraUniform {
	float view_matrix[16];
	float projection[16];
};

// Parses an embedded GLSL string into an RDShaderFile and creates a shader +
// compute pipeline from it. Mirrors NaniteHZB::init. Returns false on error.
bool _create_compute_shader_and_pipeline(RenderingDevice *p_rd, const char *p_glsl, const char *p_label,
		RID &r_shader, RID &r_pipeline) {
	Ref<RDShaderFile> shader_file;
	shader_file.instantiate();
	Error err = shader_file->parse_versions_from_text(p_glsl);
	if (err != OK) {
		shader_file->print_errors(p_label);
		return false;
	}
	r_shader = p_rd->shader_create_from_spirv(shader_file->get_spirv_stages());
	if (!r_shader.is_valid()) {
		return false;
	}
	r_pipeline = p_rd->compute_pipeline_create(r_shader);
	return r_pipeline.is_valid();
}

} // namespace

void NaniteGPUPipeline::init(RenderingDevice *p_rd) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(initialized);

	bool ok = true;
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_cull_shader_glsl, "nanite_cull", cull_shader, cull_pipeline);
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_rasterize_shader_glsl, "nanite_rasterize", rasterize_shader, rasterize_pipeline);
	ok &= _create_compute_shader_and_pipeline(p_rd, nanite_material_resolve_shader_glsl, "nanite_material_resolve", material_resolve_shader, material_resolve_pipeline);
	if (!ok) {
		ERR_FAIL_MSG("NaniteGPUPipeline: failed to create one or more compute pipelines.");
	}

	// Nearest + clamp-to-edge sampler for the HZB texture bound in the cull set.
	RD::SamplerState sampler_state;
	sampler_state.mag_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.min_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.mip_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.repeat_u = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_v = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_w = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	hzb_sampler = p_rd->sampler_create(sampler_state);
	ERR_FAIL_COND(!hzb_sampler.is_valid());

	// Persistent camera UBO (updated each frame via buffer_update).
	camera_ubo = p_rd->uniform_buffer_create(sizeof(CameraUniform));
	ERR_FAIL_COND(!camera_ubo.is_valid());

	// 1x1 R32_SFLOAT fallback for the HZB texture slot until the first HZB is
	// built (the cull shader declares sampler2D hzb_texture; the binding must
	// always point at a valid R32_SFLOAT texture).
	RD::TextureFormat dummy_tf;
	dummy_tf.format = RD::DATA_FORMAT_R32_SFLOAT;
	dummy_tf.width = 1;
	dummy_tf.height = 1;
	dummy_tf.texture_type = RD::TEXTURE_TYPE_2D;
	dummy_tf.usage_bits = RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT;
	dummy_hzb_texture = p_rd->texture_create(dummy_tf, RD::TextureView());
	ERR_FAIL_COND(!dummy_hzb_texture.is_valid());
	PackedByteArray zero;
	zero.resize(sizeof(float));
	zero.fill(0);
	p_rd->texture_update(dummy_hzb_texture, 0, zero);

	hzb.init(p_rd);

	initialized = true;
}

void NaniteGPUPipeline::_free_screen_buffers(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		vis_buffer = RID();
		depth_buffer = RID();
		color_buffer = RID();
		current_width = 0;
		current_height = 0;
		return;
	}
	if (vis_buffer.is_valid()) {
		p_rd->free_rid(vis_buffer);
		vis_buffer = RID();
	}
	if (depth_buffer.is_valid()) {
		p_rd->free_rid(depth_buffer);
		depth_buffer = RID();
	}
	if (color_buffer.is_valid()) {
		p_rd->free_rid(color_buffer);
		color_buffer = RID();
	}
	current_width = 0;
	current_height = 0;
}

void NaniteGPUPipeline::_free_visible_buffers(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		visible_clusters_buffer = RID();
		visible_count_buffer = RID();
		current_visible_capacity = 0;
		return;
	}
	if (visible_clusters_buffer.is_valid()) {
		p_rd->free_rid(visible_clusters_buffer);
		visible_clusters_buffer = RID();
	}
	if (visible_count_buffer.is_valid()) {
		p_rd->free_rid(visible_count_buffer);
		visible_count_buffer = RID();
	}
	current_visible_capacity = 0;
}

void NaniteGPUPipeline::cleanup(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		return;
	}

	_free_screen_buffers(p_rd);
	_free_visible_buffers(p_rd);

	hzb.cleanup(p_rd);

	if (dummy_hzb_texture.is_valid()) {
		p_rd->free_rid(dummy_hzb_texture);
		dummy_hzb_texture = RID();
	}
	if (camera_ubo.is_valid()) {
		p_rd->free_rid(camera_ubo);
		camera_ubo = RID();
	}
	if (hzb_sampler.is_valid()) {
		p_rd->free_rid(hzb_sampler);
		hzb_sampler = RID();
	}
	if (material_resolve_pipeline.is_valid()) {
		p_rd->free_rid(material_resolve_pipeline);
		material_resolve_pipeline = RID();
	}
	if (material_resolve_shader.is_valid()) {
		p_rd->free_rid(material_resolve_shader);
		material_resolve_shader = RID();
	}
	if (rasterize_pipeline.is_valid()) {
		p_rd->free_rid(rasterize_pipeline);
		rasterize_pipeline = RID();
	}
	if (rasterize_shader.is_valid()) {
		p_rd->free_rid(rasterize_shader);
		rasterize_shader = RID();
	}
	if (cull_pipeline.is_valid()) {
		p_rd->free_rid(cull_pipeline);
		cull_pipeline = RID();
	}
	if (cull_shader.is_valid()) {
		p_rd->free_rid(cull_shader);
		cull_shader = RID();
	}

	initialized = false;
}

void NaniteGPUPipeline::ensure_screen_buffers(RenderingDevice *p_rd, int p_width, int p_height) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(p_width <= 0 || p_height <= 0);

	if (p_width == current_width && p_height == current_height && vis_buffer.is_valid() && depth_buffer.is_valid() && color_buffer.is_valid()) {
		return;
	}

	_free_screen_buffers(p_rd);

	current_width = p_width;
	current_height = p_height;

	// vis_buffer: R32_UINT, one uint per pixel = (cluster_id << 8 | triangle_id).
	// Storage for imageStore (rasterize) + sampling/copy for downstream passes.
	RD::TextureFormat vis_tf;
	vis_tf.format = RD::DATA_FORMAT_R32_UINT;
	vis_tf.width = p_width;
	vis_tf.height = p_height;
	vis_tf.texture_type = RD::TEXTURE_TYPE_2D;
	vis_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;
	vis_buffer = p_rd->texture_create(vis_tf, RD::TextureView());
	ERR_FAIL_COND(!vis_buffer.is_valid());

	// depth_buffer: R32_SFLOAT, written by the rasterize pass and copied into
	// HZB mip 0 by dispatch_hzb_build (so it needs CAN_COPY_FROM_BIT).
	RD::TextureFormat depth_tf;
	depth_tf.format = RD::DATA_FORMAT_R32_SFLOAT;
	depth_tf.width = p_width;
	depth_tf.height = p_height;
	depth_tf.texture_type = RD::TEXTURE_TYPE_2D;
	depth_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT | RD::TEXTURE_USAGE_CAN_UPDATE_BIT;
	depth_buffer = p_rd->texture_create(depth_tf, RD::TextureView());
	ERR_FAIL_COND(!depth_buffer.is_valid());

	// color_buffer: RGBA8 UNORM, written by material_resolve (Task 1.11) and
	// read back by tests / future compositing into the engine color target.
	RD::TextureFormat color_tf;
	color_tf.format = RD::DATA_FORMAT_R8G8B8A8_UNORM;
	color_tf.width = p_width;
	color_tf.height = p_height;
	color_tf.texture_type = RD::TEXTURE_TYPE_2D;
	color_tf.usage_bits = RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;
	color_buffer = p_rd->texture_create(color_tf, RD::TextureView());
	ERR_FAIL_COND(!color_buffer.is_valid());
}

RID NaniteGPUPipeline::dispatch_cull(RenderingDevice *p_rd, const CullParams &p_params, const NaniteMeshData *p_mesh_data) {
	ERR_FAIL_NULL_V(p_rd, RID());
	ERR_FAIL_COND_V(!initialized, RID());
	ERR_FAIL_NULL_V(p_mesh_data, RID());
	ERR_FAIL_COND_V(!p_mesh_data->is_gpu_uploaded(), RID());
	ERR_FAIL_COND_V(!cull_pipeline.is_valid(), RID());

	const uint32_t cluster_count = p_params.cluster_count;

	// (Re)allocate the visible-clusters scratch buffer if it must grow. The
	// count buffer is a single uint32; it is zeroed before every dispatch.
	if (cluster_count > current_visible_capacity || !visible_clusters_buffer.is_valid() || !visible_count_buffer.is_valid()) {
		_free_visible_buffers(p_rd);

		// Zero-sized storage buffers cause driver issues, so keep at least 1.
		uint32_t capacity = MAX(cluster_count, 1u);
		visible_clusters_buffer = p_rd->storage_buffer_create(capacity * sizeof(uint32_t));
		ERR_FAIL_COND_V(!visible_clusters_buffer.is_valid(), RID());
		visible_count_buffer = p_rd->storage_buffer_create(sizeof(uint32_t));
		ERR_FAIL_COND_V(!visible_count_buffer.is_valid(), RID());
		current_visible_capacity = capacity;
	}

	// Zero the visible counter so the shader's atomicAdd starts from 0.
	uint32_t zero_count = 0;
	p_rd->buffer_update(visible_count_buffer, 0, sizeof(uint32_t), &zero_count);

	// Refresh the camera UBO with this frame's matrices (column-major float[16]).
	CameraUniform cam;
	memcpy(cam.view_matrix, p_params.view_matrix, sizeof(cam.view_matrix));
	memcpy(cam.projection, p_params.projection, sizeof(cam.projection));
	p_rd->buffer_update(camera_ubo, 0, sizeof(CameraUniform), &cam);

	// HZB texture may not exist yet on the first frame; fall back to the 1x1
	// dummy so the sampler2D binding is always valid.
	RID hzb_tex = hzb.get_hzb_texture();
	if (!hzb_tex.is_valid()) {
		hzb_tex = dummy_hzb_texture;
	}

	// Build the cull uniform set (set 0): clusters, bvh, hzb+sampler, visible
	// output, visible count, camera UBO.
	Vector<RD::Uniform> uniforms;
	{
		RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 0, p_mesh_data->get_cluster_ssbo());
		RD::Uniform u_bvh(RD::UNIFORM_TYPE_STORAGE_BUFFER, 1, p_mesh_data->get_bvh_ssbo());
		RD::Uniform u_hzb(RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE, 2, Vector<RID>({ hzb_sampler, hzb_tex }));
		RD::Uniform u_visible(RD::UNIFORM_TYPE_STORAGE_BUFFER, 3, visible_clusters_buffer);
		RD::Uniform u_count(RD::UNIFORM_TYPE_STORAGE_BUFFER, 4, visible_count_buffer);
		RD::Uniform u_camera(RD::UNIFORM_TYPE_UNIFORM_BUFFER, 5, camera_ubo);
		uniforms.push_back(u_clusters);
		uniforms.push_back(u_bvh);
		uniforms.push_back(u_hzb);
		uniforms.push_back(u_visible);
		uniforms.push_back(u_count);
		uniforms.push_back(u_camera);
	}
	RID uniform_set = p_rd->uniform_set_create(uniforms, cull_shader, 0);
	ERR_FAIL_COND_V(!uniform_set.is_valid(), RID());

	CullPushConstant pc;
	pc.screen_size[0] = p_params.screen_size[0];
	pc.screen_size[1] = p_params.screen_size[1];
	pc.error_threshold = p_params.error_threshold;
	pc.bvh_node_count = p_params.bvh_node_count;
	pc.cluster_count = cluster_count;
	pc._pad = 0;

	// dispatch_threads covers cluster_count invocations (workgroup 64).
	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, cull_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(CullPushConstant));
	p_rd->compute_list_dispatch_threads(compute_list, MAX(cluster_count, 1u), 1, 1);
	p_rd->compute_list_end();

	// Make visible_clusters_buffer / visible_count_buffer reads in the
	// following rasterize pass observe the cull writes.
	p_rd->barrier();

	return visible_clusters_buffer;
}

void NaniteGPUPipeline::dispatch_rasterize(RenderingDevice *p_rd, const RID &p_visible_buffer, uint32_t p_visible_count, const NaniteMeshData *p_mesh_data) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!p_visible_buffer.is_valid());
	ERR_FAIL_NULL(p_mesh_data);
	ERR_FAIL_COND(!p_mesh_data->is_gpu_uploaded());
	ERR_FAIL_COND(!rasterize_pipeline.is_valid());
	ERR_FAIL_COND(!vis_buffer.is_valid());
	ERR_FAIL_COND(!depth_buffer.is_valid());

	Vector<RD::Uniform> uniforms;
	{
		RD::Uniform u_visible(RD::UNIFORM_TYPE_STORAGE_BUFFER, 0, p_visible_buffer);
		RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 1, p_mesh_data->get_cluster_ssbo());
		RD::Uniform u_vertices(RD::UNIFORM_TYPE_STORAGE_BUFFER, 2, p_mesh_data->get_vertex_ssbo());
		RD::Uniform u_vis(RD::UNIFORM_TYPE_IMAGE, 3, vis_buffer);
		RD::Uniform u_depth(RD::UNIFORM_TYPE_IMAGE, 4, depth_buffer);
		uniforms.push_back(u_visible);
		uniforms.push_back(u_clusters);
		uniforms.push_back(u_vertices);
		uniforms.push_back(u_vis);
		uniforms.push_back(u_depth);
	}
	RID uniform_set = p_rd->uniform_set_create(uniforms, rasterize_shader, 0);
	ERR_FAIL_COND(!uniform_set.is_valid());

	RasterizePushConstant pc;
	pc.screen_size[0] = current_width;
	pc.screen_size[1] = current_height;
	pc.visible_count = p_visible_count;
	pc._pad = 0;

	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, rasterize_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(RasterizePushConstant));
	p_rd->compute_list_dispatch_threads(compute_list, MAX(p_visible_count, 1u), 1, 1);
	p_rd->compute_list_end();

	// vis_buffer / depth_buffer writes must be visible to dispatch_hzb_build.
	p_rd->barrier();
}

void NaniteGPUPipeline::dispatch_hzb_build(RenderingDevice *p_rd, const RID &p_depth_texture) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	hzb.build(p_rd, p_depth_texture);
}

void NaniteGPUPipeline::dispatch_material_resolve(RenderingDevice *p_rd, const RID &p_vis_buffer, const NaniteMeshData *p_mesh_data, int p_debug_mode) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!material_resolve_pipeline.is_valid());
	ERR_FAIL_COND(!vis_buffer.is_valid());
	ERR_FAIL_COND(!color_buffer.is_valid());
	ERR_FAIL_NULL(p_mesh_data);
	ERR_FAIL_COND(!p_mesh_data->is_gpu_uploaded());

	// Use the pipeline's internal vis_buffer if p_vis_buffer is invalid
	// (caller convenience — most callers drive the full pipeline internally).
	RID vis = p_vis_buffer.is_valid() ? p_vis_buffer : vis_buffer;

	// Build the material-resolve uniform set (set 0):
	//   binding 0: vis_buffer (readonly uimage2D, r32ui)
	//   binding 1: color_buffer (writeonly image2D, rgba8)
	//   binding 2: cluster_ssbo (storage buffer, for material lookup — unused in Stage 1)
	Vector<RD::Uniform> uniforms;
	{
		RD::Uniform u_vis(RD::UNIFORM_TYPE_IMAGE, 0, vis);
		RD::Uniform u_color(RD::UNIFORM_TYPE_IMAGE, 1, color_buffer);
		RD::Uniform u_clusters(RD::UNIFORM_TYPE_STORAGE_BUFFER, 2, p_mesh_data->get_cluster_ssbo());
		uniforms.push_back(u_vis);
		uniforms.push_back(u_color);
		uniforms.push_back(u_clusters);
	}
	RID uniform_set = p_rd->uniform_set_create(uniforms, material_resolve_shader, 0);
	ERR_FAIL_COND(!uniform_set.is_valid());

	MaterialResolvePushConstant pc;
	pc.screen_size[0] = current_width;
	pc.screen_size[1] = current_height;
	pc.debug_mode = (uint32_t)p_debug_mode;
	pc._pad = 0;

	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, material_resolve_pipeline);
	p_rd->compute_list_bind_uniform_set(compute_list, uniform_set, 0);
	p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(MaterialResolvePushConstant));
	// dispatch_threads covers all screen pixels (workgroup 8x8).
	p_rd->compute_list_dispatch_threads(compute_list, current_width, current_height, 1);
	p_rd->compute_list_end();
}
