/**************************************************************************/
/*  nanite_hzb.cpp                                                        */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#include "gpu/nanite_hzb.h"

#include "core/error/error_macros.h"
#include "core/math/vector3.h"
#include "servers/rendering/rendering_device.h"
#include "servers/rendering/rendering_device_binds.h"

// Generated by the GLSL_HEADER scons builder from nanite/shaders/.
// Defines `nanite_hzb_downsample_shader_glsl` (raw GLSL source string).
#include "shaders/nanite_hzb_downsample.glsl.gen.h"

namespace {

// Must match the `Params` push constant block in nanite_hzb_downsample.glsl.
struct HZBDownsamplePushConstant {
	int32_t src_size[2]; // size of the source (finer) mip
	int32_t mip_level; // destination mip level (debug only)
	int32_t pad;
};

} // namespace

void NaniteHZB::init(RenderingDevice *p_rd) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(initialized);

	// Parse the embedded GLSL and compile to SPIR-V at runtime. This mirrors
	// the pattern used by the lightmapper_rd module: a raw GLSL string is
	// turned into an RDShaderFile, then into an RD shader + compute pipeline.
	Ref<RDShaderFile> shader_file;
	shader_file.instantiate();
	Error err = shader_file->parse_versions_from_text(nanite_hzb_downsample_shader_glsl);
	if (err != OK) {
		shader_file->print_errors("nanite_hzb_downsample");
		ERR_FAIL_MSG("Failed to parse nanite_hzb_downsample GLSL");
	}

	downsample_shader = p_rd->shader_create_from_spirv(shader_file->get_spirv_stages());
	ERR_FAIL_COND(!downsample_shader.is_valid());

	downsample_pipeline = p_rd->compute_pipeline_create(downsample_shader);
	ERR_FAIL_COND(!downsample_pipeline.is_valid());

	// Nearest + clamp-to-edge sampler for texelFetch of the source mip.
	// No filtering is needed because each texel maps 1:1 to a fetch.
	RD::SamplerState sampler_state;
	sampler_state.mag_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.min_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.mip_filter = RD::SAMPLER_FILTER_NEAREST;
	sampler_state.repeat_u = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_v = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler_state.repeat_w = RD::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE;
	sampler = p_rd->sampler_create(sampler_state);
	ERR_FAIL_COND(!sampler.is_valid());

	initialized = true;
	needs_rebuild = true;
}

void NaniteHZB::_free_texture(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		downsample_uniform_sets.clear();
		hzb_mip_views.clear();
		hzb_texture = RID();
		return;
	}

	for (RID &uset : downsample_uniform_sets) {
		if (uset.is_valid()) {
			p_rd->free_rid(uset);
		}
	}
	downsample_uniform_sets.clear();

	for (RID &view : hzb_mip_views) {
		if (view.is_valid()) {
			p_rd->free_rid(view);
		}
	}
	hzb_mip_views.clear();

	if (hzb_texture.is_valid()) {
		p_rd->free_rid(hzb_texture);
		hzb_texture = RID();
	}
}

void NaniteHZB::cleanup(RenderingDevice *p_rd) {
	if (p_rd == nullptr) {
		return;
	}

	_free_texture(p_rd);

	if (downsample_pipeline.is_valid()) {
		p_rd->free_rid(downsample_pipeline);
		downsample_pipeline = RID();
	}
	if (downsample_shader.is_valid()) {
		p_rd->free_rid(downsample_shader);
		downsample_shader = RID();
	}
	if (sampler.is_valid()) {
		p_rd->free_rid(sampler);
		sampler = RID();
	}

	mip_count = 0;
	current_width = 0;
	current_height = 0;
	needs_rebuild = true;
	initialized = false;
}

void NaniteHZB::resize(RenderingDevice *p_rd, int p_width, int p_height) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(p_width <= 0 || p_height <= 0);

	int new_mip_count = compute_mip_count(p_width, p_height);
	if (!needs_rebuild && p_width == current_width && p_height == current_height && new_mip_count == mip_count) {
		return;
	}

	// Drop the old texture + views + uniform sets before reallocating.
	_free_texture(p_rd);

	mip_count = new_mip_count;
	current_width = p_width;
	current_height = p_height;

	// Single R32_SFLOAT 2D texture with a full mip pyramid. mip 0 is the
	// full-resolution base; each subsequent mip is half-res and stores the
	// MAX of its 2x2 children (written by the downsample shader).
	RD::TextureFormat tf;
	tf.format = RD::DATA_FORMAT_R32_SFLOAT;
	tf.width = p_width;
	tf.height = p_height;
	tf.texture_type = RD::TEXTURE_TYPE_2D;
	tf.mipmaps = mip_count;
	tf.usage_bits = RD::TEXTURE_USAGE_SAMPLING_BIT | RD::TEXTURE_USAGE_STORAGE_BIT | RD::TEXTURE_USAGE_CAN_COPY_TO_BIT | RD::TEXTURE_USAGE_CAN_COPY_FROM_BIT;

	hzb_texture = p_rd->texture_create(tf, RD::TextureView());
	ERR_FAIL_COND(!hzb_texture.is_valid());

	// Per-mip views so the shader can bind an individual mip level as a
	// sampler2D (src) and/or storage image (dst).
	hzb_mip_views.resize(mip_count);
	for (int i = 0; i < mip_count; i++) {
		hzb_mip_views[i] = p_rd->texture_create_shared_from_slice(RD::TextureView(), hzb_texture, 0, i, 1, RD::TEXTURE_SLICE_2D);
	}

	// Cache one uniform set per mip level (1..mip_count-1). mip 0 is never a
	// downsample destination, so its slot stays invalid. Sets are rebuilt
	// here so they stay valid as long as the texture RIDs don't change.
	downsample_uniform_sets.resize(mip_count);
	for (int i = 1; i < mip_count; i++) {
		Vector<RD::Uniform> uniforms;
		// binding 0: sampler + previous (finer) mip as a sampler2D.
		RD::Uniform u_src(RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE, 0, Vector<RID>({ sampler, hzb_mip_views[i - 1] }));
		// binding 1: current (coarser) mip as a write-only storage image.
		RD::Uniform u_dst(RD::UNIFORM_TYPE_IMAGE, 1, hzb_mip_views[i]);
		uniforms.push_back(u_src);
		uniforms.push_back(u_dst);
		downsample_uniform_sets[i] = p_rd->uniform_set_create(uniforms, downsample_shader, 0);
	}

	needs_rebuild = false;
}

void NaniteHZB::build(RenderingDevice *p_rd, const RID &p_depth_texture) {
	ERR_FAIL_NULL(p_rd);
	ERR_FAIL_COND(!initialized);
	ERR_FAIL_COND(!p_depth_texture.is_valid());

	// Derive the HZB resolution from the input depth texture so the caller
	// doesn't have to track it separately.
	Size2i depth_size = p_rd->texture_size(p_depth_texture);
	ERR_FAIL_COND(depth_size.width <= 0 || depth_size.height <= 0);

	if (needs_rebuild || depth_size.width != current_width || depth_size.height != current_height) {
		resize(p_rd, depth_size.width, depth_size.height);
	}
	ERR_FAIL_COND(!hzb_texture.is_valid());

	// Seed mip 0 with the input depth. NOTE: texture_copy requires the source
	// to be copy-compatible with R32_SFLOAT; the Nanite rasterize pass is
	// expected to provide such a texture (or a resolved float depth). When
	// the depth attachment is D32_SFLOAT and a direct copy is rejected by the
	// driver, the caller must resolve it to an R32_SFLOAT texture first — this
	// will be wired up when the rasterize pass lands in a later Stage 1 task.
	Error err = p_rd->texture_copy(p_depth_texture, hzb_texture, Vector3(0, 0, 0), Vector3(0, 0, 0), Vector3(current_width, current_height, 1), 0, 0, 0, 0);
	ERR_FAIL_COND(err != OK);

	// Make the copy visible to the subsequent compute reads of mip 0.
	p_rd->barrier();

	// Chain 8x8 compute dispatches: mip i reads mip i-1 and writes mip i.
	RD::ComputeListID compute_list = p_rd->compute_list_begin();
	p_rd->compute_list_bind_compute_pipeline(compute_list, downsample_pipeline);

	for (int i = 1; i < mip_count; i++) {
		p_rd->compute_list_bind_uniform_set(compute_list, downsample_uniform_sets[i], 0);

		HZBDownsamplePushConstant pc;
		pc.src_size[0] = MAX(current_width >> (i - 1), 1);
		pc.src_size[1] = MAX(current_height >> (i - 1), 1);
		pc.mip_level = i;
		pc.pad = 0;
		p_rd->compute_list_set_push_constant(compute_list, &pc, sizeof(HZBDownsamplePushConstant));

		// dispatch_threads covers the source mip dimensions; the shader
		// bounds-checks invocations past the source size.
		p_rd->compute_list_dispatch_threads(compute_list, pc.src_size[0], pc.src_size[1], 1);

		// mip i must finish writing before mip i+1 reads it.
		if (i < mip_count - 1) {
			p_rd->compute_list_add_barrier(compute_list);
		}
	}

	p_rd->compute_list_end();
}
